import Header from '@/components/Header'
import Nabvar from '@/components/Navbar'
import '../styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="transition-colors duration-300 dark:bg-gray-900 dark:text-white">
        <Header />
        <Nabvar />
        {children}
      </body>
    </html>
  )
}
